name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew:main

    steps:
      - name: Install cmake
        run: |
          apk add cmake

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fetch full clone
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --prune --unshallow || true

      - name: Configure project
        run: |
          cmake -B build \
            -DRELEASE=OFF \
            -DPATCHER_ENABLE_SPLASH=OFF

      - name: Build OSDMenu without KELF signing
        run: |
          cmake --build build --target osdmenu_unc

      - name: Pack OSDMenu ELF
        run: |
          echo "===== PACKING OSDMENU ====="
          ps2-packer \
            build/osdmenu/osdmenu_unc.elf \
            build/osdmenu/osdmenu.elf

      - name: Build launcher
        run: |
          cmake --build build --target launcher

      - name: Show generated files
        run: |
          echo "===== GENERATED FILES ====="
          find build -type f \( \
            -name "*.elf" -o \
            -name "*.irx" -o \
            -name "*.bin" \
          \) -print

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: osdmenu-1.3.0-splash-off
          path: |
            build/osdmenu/osdmenu.elf
            build/osdmenu/osdmenu_unc.elf
            build/launcher/launcher.elf
            build/launcher/launcher_unc.elf
            build/launcher/mmceman.irx
            build/utils/**/*.elf
          if-no-files-found: error
